name: Build and Auto Release

on:
  push:
    branches: [ main, dev ]  # 添加dev分支
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [24.x]  # 从16.x升级到24.x

    steps:
    - uses: actions/checkout@v4  # 从v3升级到v4
      with:
        fetch-depth: 0
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4  # 从v3升级到v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Build application
      run: |
        if [ "${{ matrix.os }}" == "macos-latest" ]; then
          yarn build:mac
        else
          yarn build:win
        fi
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4  # 从v3升级到v4
      with:
        name: dist-${{ matrix.os }}
        path: dist