name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  # 任务1：创建版本发布。只在 main 分支 push 时运行。
  create-tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      
      - name: Get version from package.json
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Create Tag
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const version = '${{ steps.package-version.outputs.version }}'
            const tagName = `v${version}`
            
            // 检查tag是否已存在
            try {
              await github.rest.git.getRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${tagName}`
              })
              console.log(`Tag ${tagName} already exists.`)
            } catch (error) {
              // 创建新tag
              const sha = context.sha
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${tagName}`,
                sha: sha
              })
              console.log(`Created tag ${tagName} at ${sha}`)
            }
  
  # 构建和发布应用
  release:
    # 确保此任务只在 tag 被推送到仓库时运行
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Build and publish application
      run: |
        if [ "${{ matrix.os }}" == "macos-latest" ]; then
          yarn build:mac --universal
        else
          yarn build:win
        fi
      shell: bash
    
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.exe
          dist/*universal.dmg
          dist/latest*.yml
        # 这里需要加上 tag_name，确保它知道将文件上传到哪个 Release
        tag_name: ${{ github.ref }}
        name: ${{ github.ref }}
        draft: false
        prerelease: false
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
  
  # # 发布到GitHub Packages
  # publish-package:
  #   needs: [create-release, release]
  #   if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         token: ${{ secrets.GH_TOKEN }}
      
  #     - name: Use Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '24.x'
  #         registry-url: 'https://npm.pkg.github.com'
  #         scope: '@sun-guannan'
  #         cache: 'yarn'
      
  #     - name: Install dependencies
  #       run: yarn install --frozen-lockfile
      
  #     - name: Create .npmrc file
  #       run: |
  #         echo "@sun-guannan:registry=https://npm.pkg.github.com/" > .npmrc
  #         echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" >> .npmrc
      
  #     - name: Configure package for GitHub Packages
  #       run: |
  #         # 确保包名与仓库名完全匹配（包括大小写）
  #         node -e "const pkg=require('./package.json'); pkg.name='@sun-guannan/capcutmaker'; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2))"
      
  #     - name: Publish to GitHub Packages
  #       run: npm publish --access=public
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
  
  # # 上传自动更新文件到 GitHub Releases
  # publish-update-files:
  #   needs: [create-release, release]
  #   if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         token: ${{ secrets.GH_TOKEN }}
      
  #     - name: Download artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         path: ./artifacts
      
  #     - name: List downloaded artifacts
  #       run: find ./artifacts -type f | sort
      
  #     - name: Get version from package.json
  #       id: package-version
  #       run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: dist-${{ matrix.os }}
  #         path: |
  #           dist/*.exe
  #           dist/*.dmg
  #           dist/latest*.yml
  #           dist/latest*.yaml
      
  #     - name: Upload update files to release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         tag_name: v${{ steps.package-version.outputs.version }}
  #         files: |
  #           ./artifacts/**/latest*.yml
  #           ./artifacts/**/latest*.yaml
  #         draft: false
  #         prerelease: false
  #       env:
  #         GH_TOKEN: ${{ secrets.GH_TOKEN }}