name: Release

on:
  push:
    branches:
      - main
      
jobs:
  # 创建版本发布
  create-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      
      - name: Get version from package.json
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Create Tag and Release 
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const version = '${{ steps.package-version.outputs.version }}'
            const tagName = `v${version}`
            
            // 检查tag是否已存在
            try {
              await github.rest.git.getRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${tagName}`
              })
              console.log(`Tag ${tagName} already exists.`)
            } catch (error) {
              // 创建新tag
              const sha = context.sha
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${tagName}`,
                sha: sha
              })
              console.log(`Created tag ${tagName} at ${sha}`)
              
              // 创建GitHub Release
              await github.rest.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: tagName,
                name: `Release ${tagName}`,
                body: `Release version ${version}`,
                draft: false,
                prerelease: false
              })
              console.log(`Created release for ${tagName}`)
            }
  
  # 构建和发布应用
  release:
    needs: create-release
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Build and publish application
      run: |
        if [ "${{ matrix.os }}" == "macos-latest" ]; then
          yarn build:mac --universal --publish always
        else
          yarn build:win --publish always
        fi
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.exe
          dist/*universal.dmg
          dist/latest*.yml
        draft: false
        prerelease: false
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
  
  # 发布到GitHub Packages
  publish-package:
    needs: [create-release, release]
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@sun-guannan'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Create .npmrc file
        run: |
          echo "@sun-guannan:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" >> .npmrc
      
      - name: Configure package for GitHub Packages
        run: |
          # 确保包名与仓库名完全匹配（包括大小写）
          node -e "const pkg=require('./package.json'); pkg.name='@sun-guannan/capcutmaker'; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2))"
      
      - name: Publish to GitHub Packages
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}